project:
  type: website
  output-dir: docs
  
website:
  title: "Kristin Abijaoude"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/kabijaoude/KristinsBlog/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Kristin Abijaoude"

format:
  html:
    theme: cerulean
    toc: true

editor: source

